name: Deploy Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.x
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Serverless and dependencies
        run: |
          npm i -g serverless
          
      - name: Deploy using Serverless
        run: |
          chmod 755 ./scripts/deploy_dev.sh
          ./scripts/deploy_dev.sh